version: '3.7'
services:
  python-base:
    image: stagybee/python-base:slim
    build:
      context: python-base/
  db:
    image: postgres:12.1-alpine
    volumes:
      - type: bind
        source: ./data
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=stagybee
      - POSTGRES_PASSWORD=stagybee
      - POSTGRES_DB=stagybee_dev
  redis:
    image: redis:alpine
  #extractor:
  #  build:
  #    context: ../extractor/   # change accordingly
  #    dockerfile: Dockerfile
  #  image: "stagybee/extractor:latest"
  #  restart: always
  #  expose:
  #    - 5000
  web:
    build:
      context: app/
    image: "stagybee/frontend:latest"
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
  #   - extractor
    volumes:
      - type: bind
        source: ./app/shutdown_signal
        target: /home/pyuser/shutdown_signal
