version: '3.7'
services:
  nginx:
    build:
      context: nginx/
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - type: volume
        source: static_data
        target: /home/pyuser/static
  web:
    build:
      context: app/
      dockerfile: Dockerfile.prod
    image: "stagybee/frontend:latest"
    command: bash -c "daphne -b 0.0.0.0 -p 8000 stagy_bee.asgi:application"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
      - db
    expose:
      - 8000
    volumes:
      - type: volume
        source: static_data
        target: /home/pyuser/static
      - "/var/run/shutdown_signal:/shutdown_signal"

volumes:
  static_data: