version: '3.7'
services:
  python-base:
    image: stagybee/python-base:slim
    build:
      context: python-base/
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=stagybee
      - POSTGRES_PASSWORD=stagybee
      - POSTGRES_DB=stagybee_dev
  redis:
    image: redis:alpine
    networks:
      - stagybee-net-back
    ports:
      - "6379:6379"
  web:
    build:
      context: app/
    image: "stagybee/frontend:latest"
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
    networks:
      - stagybee-net
      - stagybee-net-back
    depends_on:
      - redis
      - db
    links:
      - redis
    volumes:
      - "/var/run/shutdown_signal:/shutdown_signal"

networks:
  stagybee-net:
    name: "stagybee-net"
    driver: bridge
  stagybee-net-back:
    name: "stagybee-net-back"
    driver: bridge

volumes:
  postgres_data:
