version: '3.7'
services:
  db:
    restart: always
  redis:
    restart: always
  nginx:
    build:
      context: nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - type: bind
        source: ./static
        target: /home/pyuser/static
  web:
    build:
      context: app/
      dockerfile: Dockerfile.prod
    image: "stagybee/frontend:latest"
    command: bash -c "daphne -b 0.0.0.0 -p 8000 stagy_bee.asgi:application"
    restart: always
    expose:
      - 8000
    volumes:
      - type: bind
        source: ./static
        target: /home/pyuser/static
      - "/var/run/shutdown_signal:/shutdown_signal"
